// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file JointTrajectoryPublisher.h
 * This header file contains the declaration of the publisher functions.
 *
 * This file was generated by the tool fastcdrgen.
 */


#ifndef _JOINTTRAJECTORY_PUBLISHER_H_
#define _JOINTTRAJECTORY_PUBLISHER_H_

#include <fastrtps/fastrtps_fwd.h>
#include <fastrtps/publisher/PublisherListener.h>

#include "JointTrajectoryPubSubTypes.h"

using namespace eprosima::fastrtps;

class JointTrajectoryPublisher 
{
public:
	JointTrajectoryPublisher();
	virtual ~JointTrajectoryPublisher();
	bool init();
	void run();

    static void fillTraj(MyMsg::JointTrajectory& traj);

private:
	Participant *participant_;
	Publisher *publisher_;
	
	class PubListener : public PublisherListener
	{
	public:
		PubListener() : matched_(0) {};
		~PubListener() {};
		void onPublicationMatched(Publisher* pub, MatchingInfo& info);
		int matched_;
	} listener_;
	JointTrajectoryPubSubType myType_;
};

#endif // _JOINTTRAJECTORY_PUBLISHER_H_